# Use the official .NET runtime as a parent image
FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine3.23 AS base
WORKDIR /app
EXPOSE 5220

# Use the .NET SDK for building
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY api.csproj .
RUN dotnet restore
COPY . .
RUN dotnet build -c Release -o /app/build

# Publish the application
FROM build AS publish
RUN dotnet publish -c Release -o /app/publish

# Final stage
FROM base AS final
WORKDIR /app

RUN apk upgrade --no-cache libcrypto3 libssl3

COPY --from=publish /app/publish .

# Create directory for SQLite database
ENV ConnectionStrings__DefaultConnection="Data Source=/app/data/consent.db"

ENTRYPOINT ["dotnet", "api.dll"]
